<tr>
  <th>Recipient Name</th>
  <td> <input type="text" readonly name="" class="input1" value="<?php echo $name ?>"> </td>
</tr>
<tr>
  <th>Recipient Fathers Name</th>
  <td> <input type="text" readonly class="input1" name="" value="<?php echo $fname ?>"> </td>
</tr>
<tr>
  <th>Amount</th>
  <td><input type="number" class="input1" name="amount" value=""> </td>
</tr>
<tr>
  <th>Details</th>
  <td> <input type="text" class="input1" name="remarks" value=""> </td>
</tr>
<tr>
  <th colspan="2" style="text-align:center"> <input class="simplebutton" type="submit" name="pay" value="Pay"> </th>
</tr>
