<h1 style="text-align:justify; width:100%">About us</h1>
<hr>
<dl>
<dt><h2>Profile</h2></dt>
<dd>The Housing Development Finance Corporation Limited (HDFC) was amongst the first to receive an 'in principle' approval from the Reserve Bank of India (RBI) to set up a bank in the private sector, as part of RBI's liberalisation of the Indian Banking Industry in 1994. The bank was incorporated in August 1994 in the name of 'HDFC Bank Limited', with its registered office in Mumbai, India. HDFC Bank commenced operations as a Scheduled Commercial Bank in January 1995.</dd>


<dt><h2>Awards</h2></dt>
<dd>
  <ul>
    <li>HDFC Bank began operations in 1995 with a simple mission: to be a "World-class Indian Bank". We realised that only a single-minded focus on product quality and service excellence would help us get there. Today, we are proud to say that we are well on our way towards that goal.
</li>
<li>It is extremely gratifying that our efforts towards providing customer convenience have been appreciated both nationally and internationally.
  </li>
</ul>
</dd>

<dt><h2>finiancial info</h2></dt>
<dd>
The last eighteen years have been very fulfilling. We can of course wax eloquent about it in so many ways, but they say, figures don't lie, so we will let the figures do all the talking. They will give you a fair idea of how we have grown in the past few years.

 <ul>
    <h3>Financial Results</h3>
  <li>RBI Order of Amalgamation - CBoP</li>
  <li>Scheme of Amalgamation - CBoP (as approved by RBI)</li>
  <li>Annual Reports</li>
  <li>Extra Ordinary General Meeting</li>
  <li>Investor Presentation</li>
  <li>Analyst Meet</li>
  <li>Postal Ballot March 2014</li>
  <li>Postal Ballot Result March 2014</li>
  <li>Postal Ballot Notice Nov.-Dec.2014</li>
  <li>Postal Ballot Result Nov.-Dec.2014</li>
</ul>
</dd>


<dt><h2>careers</h2></dt>
<dd>
  <ul>
    <li><p>
      HDFC Bank is a young and dynamic bank, with a youthful and enthusiastic team determined to accomplish the vision of becoming a world-class Indian bank.</p>
    </li>
    <li><p>
      Our business philosophy is based on five core values - Operational Excellence, Customer Focus, Product Leadership, People and Sustainability. We believe that the ultimate identity and success of our bank will reside in the exceptional quality of our people and their extraordinary efforts. For this reason, we are committed to hiring, developing, motivating and retaining the best people in the industry.</p>
    </li>
</ul>
</dd>

<dt><h2>Privacy Policy</h2></dt>
<dd><em>Who is covered under this Policy?</em>

<strong>Information covered by this Policy </strong>
<ul> <p>This Policy seeks to cover personal information of the Covered Persons provided to HDFC Bank as also any information collected by the bank server from the visitor's browser. The ("Information"), i.e. any of the following:</p>

  <li>Personal/private information of the Covered Persons
  Sensitive personal data or information</li>
  <p></strong>Definitions used in this policy:</strong></p>
<li>"Personal information" means any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available with a body corporate, is capable of identifying such person.</li>
<br>
<li>"Sensitive personal data or information" of a person means such personal information which consists of information relating to:-
  <p>password;</p>
  <p>financial information such as Bank account or credit card or debit card or other payment instrument details;</p>
  <p>physical, physiological and mental health condition;</p>
<p>medical records and history;</p>
  Biometric information;</li>
</dd>


<dt><h2>WEb usage terms</h2></dt>
<dd>
  <ul>
    <li>
      <p>
  I understand and accept that HDFC Bank maintains the web-site http://www.hdfcbank.com (going ahead referred to as "the Site" or "the bank website") to provide visitors with information about HDFC Bank, its services and products and to facilitate communication with HDFC Bank and availing its services. I also accept that visitors to the Site are required to read the below terms, and use of the Site constitutes my acceptance and agreement to be bound by such terms, and the changes therein to the Website Usage Terms from time to time, relating to my usage of the website as communicated and made available on the Bank's website.
  </p> </li>
  <li><p>
  I am aware and accept that all information, content, materials, products (including, but not limited to text, content, photographs, graphics, video and audio content) on the website is protected by copyright in the favour of HDFC Bank under applicable copyright laws and is also protected otherwise under general intellectual property law.</p></li>

  <li><p>
  I understand and accept that all information submitted by me through the HDFC Bank website shall be deemed the property of HDFC Bank, and the Bank shall be free to use any ideas, concepts, know-how or techniques provided by me at the Site, in any manner whatsoever. On initiating a contact through the Bank website I agree to being contacted by the bank or any other entities with whom the bank has entered into an arrangement.</p></li>

  <li><p>
  I agree that I shall not copy, reproduce, sell, redistribute, publish, enter into a database, display, perform, modify, transmit, license, create derivatives from, transfer or in any way exploit any part of any information, content, materials, services available from or through the bank website, except that which I may download for my own personal, non-commercial use.</p></li>

  <li><p>
  I agree that I will not use the bank website for any purpose that is unlawful, or prohibited by these Website Usage Terms. I also agree I will not use the bank website in any manner that could damage, disable or impair the website or interfere with any other party's use or enjoyment of the website.</p></li>

  <li><p>
  I acknowledge that the software and hardware underlying the bank Website as well as other Internet related software which are required for accessing the website are the legal property of the respective Vendors/Bank. The permission given by the Bank to access the bank website will not convey any proprietary or ownership rights in the above software / hardware. I agree that I shall not attempt to modify, translate, disassemble, decompile or reverse engineer the software / hardware underlying the bank website or create any derivative product based on the software / hardware.</p></li>
  </ul>
</dd>


<dt><h2>Terms & Conditions</h2></dt>
<dd>
<!-- <ol> -->
 <li><p>I agree to abide by the Bank's Terms and Conditions and rules in force and the changes thereto in Terms and Conditions from time to time relating to my account as communicated and made available on the Bank's website.</li></p>
<li><p>I agree that the opening and maintenance of the account is subject to rules and regulations introduced or amended from time to time by the Reserve Bank of India.
  </li></p>
<li><p>	I agree that the bank before opening any deposit account, will carry out a due diligence as required under Know Your Customer guidelines of the bank. I would be required to submit necessary documents or proofs, such as identity , address, photograph and any such information to meet with KYC, AML or other statutory/regulatory requirements.</p>
<p>
Further, after the account is opened, in compliance with the extant regulatory guidelines, I agree to submit the above documents again at periodic intervals, as may be required by the Bank.
</li></p>
<li><p>I agree that the Bank may, at its discretion, engage the services of Business Facilitators (hereinafter referred to as "BF") and Business Correspondents (hereinafter referred to as "BC") for extension of banking and financial services so as to ensure greater financial inclusion and increasing the outreach of the banking sector. The Bank, however, shall be responsible for the acts and omission of such BC and BF.</li></p>
<li><p>	I agree that, under normal circumstances, the bank has the liberty to close my account at any time by giving me at least 30 days notice. However, if the Average Monthly/ Quarterly Balance, is not maintained, the Bank reserves the right to close my account without giving any prior notice.</li></p>
<li><p>	I agree that the Bank can at its sole discretion, amend any of the services/facilities given in my account either wholly or partially at any time by giving me at least 30 days notice and/or provide an option to me to switch to other services/facilities.</li></p>
<li><p>	I agree that any change in my account status or change of address will be immediately informed to the Bank failing which I shall be responsible for any non-receipt of communication/deliverables or the same being delivered at my old address.</li></p>
<li><p>	I agree that all instructions relating to my account will be issued to the Bank as per acceptable mode of communication to the Bank.</li></p>
<li><p>	I agree to preserve my cheque book/ATM Card carefully. In case of loss/theft of the same I shall immediately inform the Bank in writing.
<li><p>	I agree that I will maintain the minimum balance in my account as prescribed by the Bank from time to time.
</li></p>
<!-- </ol> -->
</dd>
</dl>
