<h1 style="text-align:justify; width:100%">About Net Banking</h1>
<hr>
<dl>
 <dt><h2>What exactly is net banking</h2></dt>
 <dd>
Online banking, also known as internet banking, it is an electronic payment system that enables customers of a bank or other financial institution to conduct a range of financial transactions through the financial institution's website. The online banking system will typically connect to or be part of the core banking system operated by a bank and is in contrast to branch banking which was the traditional way customers accessed banking services.
Today, "virtual banks" (or “direct banks”) have only an internet presence, which enables them to lower costs than traditional brick-and-mortar banks.
</dd>
<dt> <h2>Features</h2> </dt>
 <dd><p>Online banking facilities typically have many features and capabilities in common, but also have some that are application specific. The common features fall broadly into several categories:
<p>
<ul>
  <p><strong>A bank customer can perform non-transactional tasks through online banking, including:</strong>
</p>
<li>Viewing account balances
</li>
<li>Viewing recent transactions
</li>
<li>Downloading bank statements, for example in PDF format
</li>
<li>Viewing images of paid cheques
</li>
<li>Ordering cheque books</li>
<li>Download periodic account statements</li>
<li>Downloading applications for M-banking, E-banking etc.</li>
<br>
<p> <strong>Bank customers can transact banking tasks through online banking, including:</strong> </p>
<li>Funds transfers between the customer's linked accounts</li>
<li>Paying third parties, including bill payments (see, e.g., BPAY) and third party fund transfers (see, e.g., FAST)
</li>
<li>Investment purchase or sale</li>
<li>Loan applications and transactions, such as repayments of enrollments
</li>
<li>Credit card applications
</li>
<li>Register utility billers and make bill payments
</li>
<li>Financial institution administration
</li>
<li>Management of multiple users having varying levels of authority
</li>
<li>Transaction approval process
</li>
<li>Some financial institutions offer special internet banking services, for example:
</li>
<li>Personal financial management support, such as importing data into personal accounting software. Some online banking platforms support account aggregation to allow the customers to monitor all of their accounts in one place whether they are with their main bank or with other institutions.
</li>

</ul>
</dd>

<dt> <h2>Advantages</h2> </dt>
 <dd>
    <p>There are some advantages to using e-banking both for banks and customers:
</p>
<ul>
  <li>Permanent access to the bank
</li>
  <li>Access anywhere using mobile or computer
</li>
  <li>Less time consuming
</li>
<li>Very safe and secure method</li>
<li>Helps to transfer the money immediately and accurately
</li>
<li>Easy to use</li>
</ul>
 </dd>



</dl>
